#!/bin/bash

#############################################################################################################################
## Harinder Gakhal                                                                                                         ##
## CSE 224                                                                                                                 ##
## 10/04/2018                                                                                                              ##
## Programming Assignment 1                                                                                                ##
## This BASH script is a text based game that will challenge a player to be the last one to remove sticks from a set.      ##
## The user will decide how many sticks to start off with as well as decide whether the computer goes first, or the users. ##
## Once the last sick is taken out, the winner will be decided.                                                            ##
#############################################################################################################################

#FUNCTIONS

# Show the number of sticks left
printSticks()
{
	for i in `seq 1 $totalSticks`
	do
		echo -n "|"
	done
	echo " ($totalSticks)"
}

# Greeting 
echo
echo "Welcome to the stick game!"
echo
echo "How this game works:"
echo "2 players take turns picking either 1, 2 or 3 sticks from a pile. Whoever picks the last stick wins."

# How many sticks
echo "How many sticks do you want to start with? (must be an integer >= 10)"
flag=0
while [ $flag == 0 ]
do
	read totalSticks
	if (( $((totalSticks)) < 10 )); 							# Check if more than 10
	then
		echo "Your number must be greater than or equal to 10!"
	else
		if ! [[ $totalSticks =~ ^-?[0-9]+$ ]];					# Makes sure whats entered is an integer
		then
			echo "Your input is not an integer!"
		else
			flag=1
		fi
	fi
done

# Who goes first
echo "Who should go first? (enter c computer or u for user)"
flag=0
while [ $flag == 0 ]
do
	read whoGoes
	if [[ ($whoGoes == 'c') || ($whoGoes == 'u') ]];			# Only can be either c or u
	then
		flag=1
		if [[ $whoGoes == 'c' ]];
		then
			echo "Great! The computer will start it off!"
		else
			echo "Great! You will start it off!"
		fi
	else
		echo "Please enter c computer or u for user."
	fi
done

# Print Inital stick amount
printSticks

# Back and forth from the player to the computer
flag=0
while [[ $flag == 0 ]];
do
	# User goes
	if [[ $whoGoes == 'u' ]];
	then
		echo "It is your turn! How many sticks would you like to take? 1, 2 or 3?"
		read uTakeout
		if (( ( $uTakeout <= 3 ) && ( $uTakeout >= 1 ) ));
		then
			totalSticks=$(($totalSticks-$uTakeout))

			# Check if won
			if [[ $totalSticks == 0 ]]; 						# If winner, end game
			then
				break
			fi
			printSticks
		else
			echo "Please choose 1, 2, or 3 sticks to take out. You have one more try."
			read uTakeout
			if !(( ( $uTakeout <= 3 ) && ( $uTakeout >=1 ) ));	# User will have 1 more try to enter valid number
			then
				echo "You have entered an invalid number."
				echo "Quitting game..."
				exit
			else
				totalSticks=$((totalSticks-uTakeout))
				printSticks
			fi
		fi
		whoGoes='c'
	fi

	# Computer Goes
	if [[ $whoGoes == 'c' ]];
	then
		echo "Now its my turn!"									# Makes the computer more life like
		echo -n "Thinking"
		sleep .5
		echo -n "."
		sleep .5
		echo -n "."
		sleep .5
		echo "."

		cTakeout=$((totalSticks % 4))
		if [[ $cTakeout == 0 ]];
		then
			echo "Taking out 1 stick."
			totalSticks=$((totalSticks-1))

			# Check if won
			if [[ $totalSticks == 0 ]]; 						# If winner, end game
			then
				break
			fi
		else
			echo "Taking out $cTakeout sticks."
			totalSticks=$((totalSticks-cTakeout))

			# Check if won
			if [[ $totalSticks == 0 ]]; 						# If winner, end game
			then
				break
			fi
		fi
		printSticks
		whoGoes='u'
	fi
done

printSticks
# Declare winner
if [[ $whoGoes == 'u' ]]; 
then
	echo "You won!"
else
	echo "The computer won!"
fi
