#!/bin/bash

#	Harinder Gakhal
#	10/05/2018
#	CSE 224
#	ODP404
#	Write a script that accepts 2 command line arguments ( script word number )
#	If numbers is less than 1, your script shouldn't print anything

if [[ $2 < 1 ]];
then
	exit
else
	for (( i = 0; i < $2; i++ )); 
	do
		echo $1
	done
fi