#!/bin/bash

#	Harinder Gakhal
#	10/05/2018
#	CSE 224
#	ODP403
#	For ODP403, you should write a script that reads one line of input,
#	interprets that input as an integer, and prints 2* that integer

read x
echo `expr $x \* 2`